#!/usr/bin/env bash
# gen_build_info.sh — reads the VERSION file and writes Source/BuildInfo.h
# with the current version string and an unambiguous UTC build timestamp.
# CMake runs this automatically before compiling the LoopBreaker target.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERSION_FILE="$SCRIPT_DIR/VERSION"
OUTPUT_FILE="$SCRIPT_DIR/Source/BuildInfo.h"

if [[ ! -f "$VERSION_FILE" ]]; then
    echo "ERROR: VERSION file not found at $VERSION_FILE" >&2
    exit 1
fi

VERSION=$(cat "$VERSION_FILE" | tr -d '[:space:]')
BUILD_TIMESTAMP=$(TZ=UTC date '+%Y-%m-%d %H:%M UTC')

cat > "$OUTPUT_FILE" << HEADER
// BuildInfo.h -- AUTO-GENERATED by gen_build_info.sh -- DO NOT EDIT MANUALLY
// Re-generated on every build.  Commit VERSION, not this file.
#pragma once

#define LOOP_BREAKER_VERSION         "${VERSION}"
#define LOOP_BREAKER_BUILD_TIMESTAMP "${BUILD_TIMESTAMP}"
HEADER

echo "[gen_build_info] v${VERSION}  built ${BUILD_TIMESTAMP}"
