// BuildInfo.h -- AUTO-GENERATED by gen_build_info.sh -- DO NOT EDIT MANUALLY
// Re-generated on every build.  Commit VERSION, not this file.
#pragma once

#define LOOP_BREAKER_VERSION         "1.0.0"
#define LOOP_BREAKER_BUILD_TIMESTAMP "Jul 17 2026  01:43 PM EDT"
